# -*- coding: utf-8 -*-
"""07 - pandas-transformacao-manipulacao-dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ma_1uDV4cGZ9L9NLy3zp-KdUrvS42IU
"""

url_hospedagem = 'https://caelum-online-public.s3.amazonaws.com/2928-transformacao-manipulacao-dados/dados_hospedagem.json'
url_moveis = 'https://caelum-online-public.s3.amazonaws.com/2928-transformacao-manipulacao-dados/moveis_disponiveis.json'

import pandas as pd

dados = pd.read_json(url_hospedagem)
dados.head()

dados = pd.json_normalize(dados['info_moveis'])
dados

colunas = list(dados.columns)
colunas

dados = dados.explode(colunas[3:])

dados.reset_index(inplace=True, drop=True)
dados.head()

dados.info()

import  numpy as np

dados['max_hospedes'].astype(np.int64)

dados['max_hospedes'] = dados['max_hospedes'].astype(np.int64)

dados.info()

col_numericas = ['quantidade_banheiros','quantidade_quartos','quantidade_camas']
dados[col_numericas] = dados[col_numericas].astype(np.int64)
dados.info()

dados['avaliacao_geral'] = dados['avaliacao_geral'].astype(np.float64)
dados.info()

dados['preco'] = dados['preco'].apply(lambda x: x.replace('$', '').replace(',','').strip())

dados['preco'] = dados['preco'].astype(np.float64)
dados.info()

dados[['taxa_deposito','taxa_limpeza']]

dados[['taxa_deposito','taxa_limpeza']] = dados[['taxa_deposito','taxa_limpeza']].applymap(lambda x: x.replace('$', '').replace(',','').strip())
dados.info()

dados['descricao_local']

dados['descricao_local'].str.lower()

dados['descricao_local'] = dados['descricao_local'].str.lower()
dados.head()

dados['descricao_local'][3169]

dados['descricao_local'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)

dados['descricao_local'] = dados['descricao_local'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)

dados['descricao_local'].str.replace('(?<!\w)-(?!\w)', '', regex=True)

dados['descricao_local'] = dados['descricao_local'].str.replace('(?<!\w)-(?!\w)', '', regex=True)

dados['descricao_local'].str.split()

dados['descricao_local'] = dados['descricao_local'].str.split()
dados.head()

dados['comodidades'].str.replace('\{|}|\"','',regex=True)

dados['comodidades'] = dados['comodidades'].str.replace('\{|}|\"','',regex=True)

dados['comodidades'] = dados['comodidades'].str.split(',')
dados.head()

dt_data = pd.read_json(url_moveis)
dt_data.head()

dt_data.info()

pd.to_datetime(dt_data['data'])

dt_data['data'] = pd.to_datetime(dt_data['data'])

dt_data.info()

dt_data.head()

dt_data['data'].dt.strftime('%Y-%m')

dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()

subset = dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
subset

