FROM ubuntu:latest

EXPOSE 8000

WORKDIR /app

ENV HOST=localhost PORT=5432

ENV USER=root PASSWORD=root DBNAME=root

COPY ./DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/main main

CMD [ "./main" ]