name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: programa
          path: ./DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: jeffersonsilverio
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/DockerFile
          push: true
          tags: jeffersonsilverio/go_ci:${{github.ref_name}}

      