name: Go

on:
  push:
    branches: [ "continuos-integration" ]
  pull_request:
    branches: [ "master" ]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        env:
          HOST: localhost
          PORT: 5432
          USER: root
          PASSWORD: root
          DBNAME: root
        strategy:
            matrix:
                go_version: ['>=1.18']
                os: ['ubuntu-latest']
                
        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: ${{ matrix.go_version }}
        
        - name: Create-DB
          working-directory: ./DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/ 
          run: docker-compose -f "docker-compose.yml" up -d --build
          
        - name: Test
          working-directory: ./DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/ 
          run: go test -v main_test.go
      
    build:
        needs: test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                go_version: ['>=1.18']
                os: ['ubuntu-latest']

        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: ${{ matrix.go_version }}
      
        - name: Build
          working-directory: ./DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/ 
          run: go build -v main.go

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.0
          with:
            name: programa
            path: ./DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/main
    
    docker:
      needs: build
      uses: ./.github/workflows/dockerGo.yml
      secrets: inherit

