name: Go

on:
  push:
    branches: [ "continuos-integration" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Build-DB
      run: docker-compose build DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/
      
    - name: Create-DB
      run: docker-compose up -d DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/
      
    - name: Test
      run: go test -v DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/main_test.go
      
    - name: Build
      run: go build -v DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/main.go
      
  build:
      needs: test
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
     
      - name: Build
        run: go build -v DevOps/CI/integracao-continua-testes-automatizados-pipeline-github-actions/src/main.go
